// <auto-generated />
using System;
using Agendamento01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agendamento01.Migrations
{
    [DbContext(typeof(AgendamentoContext))]
    [Migration("20250802185259_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agendamento01.Alunos.Model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AulasAgendadas")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteAulas")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plano")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Agendamento01.Aulas.Model.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParticipantesAtuais")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("Agendamento01.Aulas.Model.Aula", b =>
                {
                    b.HasOne("Agendamento01.Alunos.Model.Aluno", null)
                        .WithMany("AulasRealizadas")
                        .HasForeignKey("AlunoId");
                });

            modelBuilder.Entity("Agendamento01.Alunos.Model.Aluno", b =>
                {
                    b.Navigation("AulasRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
